version: "3"
services:
  mongo:
    image: mongo
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      # - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - ./dump/testdata.js:/home/mongo-init.js:ro
      - ./dump/load_testdata.sh:/docker-entrypoint-initdb.d/load_testdata.sh:ro
      - mongodata:/data/db
    networks:
      - backend
  sportup:
    image: node
    # restart: always
    build:
      context: .
      dockerfile: node.Dockerfile
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - EXPRESS_SESSION_SECRET="my secret"
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ./app.js:/usr/src/app/app.js
      - ./index.js:/usr/src/app/index.js
      - ./models:/usr/src/app/models
      - ./updates:/usr/src/app/updates
      - ./views:/usr/src/app/views
      - ./public:/usr/src/app/public
      - ./routes:/usr/src/app/routes
      - ./services:/usr/src/app/services

    networks:
      - backend
networks:
  backend:
    driver: "bridge"

volumes:
  mongodata:    

